version: '3'

services:
  words:
    image: words
    restart: always
    # networks: 
      # - net_words
  
  db:
    image: db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    # networks:
      # - net_words
  
  web:
    image: web
    restart: always
    ports:
      - "8080:80"
    # networks:
      # - net_words
  
# networks:
  # net_words: